name: Build and Store Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build Repositories
        run: |
          cd crud
          mvn clean install -DskipTests
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crud
          path: target/mesh-storage-layer.jar
