name: Merge Latest Release to Develop

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every day at midnight
  push:
    branches:
      - main 

jobs:
  merge-release-to-develop:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout dm-parent
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          repository: KaranMesh/testrepo2
          path: testrepo2
      - name: Find latest release branch
        id: latest-release
        run: |
          cd testrepo2
          git show-ref -d
          LATEST_RELEASE=$(git for-each-ref --format="%(refname:short)" | grep -E 'origin/release/[0-9]{4}-[0-9]{2}-[0-9]{2}' | sed 's/^origin\///' | sort -r | head -n 1)
          echo "::set-output name=latest_release::$LATEST_RELEASE"

      - name: Merge latest release into develop
        run: |
          cd testrepo2
          git fetch origin temp/develop
          git checkout temp/develop
          LATEST_RELEASE=${{ steps.latest-release.outputs.latest_release }}
          if git merge --ff-only $LATEST_RELEASE; then
            git push origin temp/develop
            echo "Merged $LATEST_RELEASE into develop"
          else
            if [ $? -eq 128 ]; then
              echo "No new changes to merge. Workflow continues."
            else
              echo "Merge conflict detected. Workflow will fail."
              exit 1  # Exit with a non-zero status code to indicate failure
            fi
          fi
