name: Build and Store Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-repositories:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [testrepo2, testRepo] # Add the names of all the repositories you want to build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "KaranMesh/${{ matrix.repo }}" # Checkout the current repository
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build Repository
        run: |
          cd ..
          cd ${{ matrix.repo }} # Change directory to the current repository
          cd crud
          mvn clean install -DskipTests
      - name: Store Artifact
        if: matrix.repo == 'testRepo'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.repo }}-artifact # Add the repository name to the artifact name
          path: ${{ matrix.repo }}/crud/target/crud-0.0.1-SNAPSHOT.jar
          
  deploy:
    needs: build-repositories
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-artifact # Use the current repository name to download the artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} #This is referred from Github Secrets
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #This is referred from Github Secrets
          use_existing_version_if_available: true
          application_name: webapp-service #Application name we created in Elastic BeanStalk
          environment_name: meshai-dev12 #Environment name we created in Elastic BeanStalk
          version_label: ${{github.SHA}}
          region: ${{ secrets.AWS_REGION }} #VERY IMPORTANT: AWS Region where initially Applciation was created in AWS EBS. We created in us-east-1 which is N-Virginia
          deployment_package: crud-0.0.1-SNAPSHOT.jar # Use the current repository name to set the deployment package name
