name: Build and Store Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build Repositories
        run: |
          cd crud
          mvn clean install -DskipTests
          cd target
          ls -al
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crud
          path: crud/target/crud-0.0.1-SNAPSHOT.jar
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/elastic-beanstalk-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          application-name: meshai-dev12-test
          environment-name: meshai-dev12
